// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.5.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `delegate`, `inner_other`, `inner`

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

Stream<Progress> wordsOncecell() =>
    RustLib.instance.api.crateApiSimpleWordsOncecell();

Stream<Progress> words() => RustLib.instance.api.crateApiSimpleWords();

class Progress {
  final int current;
  final int max;
  final String word;

  const Progress({
    required this.current,
    required this.max,
    required this.word,
  });

  @override
  int get hashCode => current.hashCode ^ max.hashCode ^ word.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Progress &&
          runtimeType == other.runtimeType &&
          current == other.current &&
          max == other.max &&
          word == other.word;
}
